### PR TITLE
Upgrade python client deps

### LINKED ISSUE #55: Passing page options to the API
Hello, 
The Anvil docs mention you can pass page parameters to the APi in the following section:
[https://www.useanvil.com/docs/api/generate-pdf/#generating-a-pdf](https://www.useanvil.com/docs/api/generate-pdf/#generating-a-pdf)

However, it seems like the `GeneratePDFPayload` model on this client does not let you pass in those options. 
What's the expected way to do this currently using this client? 
Thank you!

### LINKED ISSUE #56: Pydantic 2.0 support
Pydantic 2.0 was recently [released](https://docs.pydantic.dev/latest/changelog/)

This library currently depends on [Pydantic 1.8.2](https://github.com/anvilco/python-anvil/blob/master/pyproject.toml#L46). This makes it incompatible with projects using Pydantic 2.0

Is there any appetite to upgrade the dependency to v2? The migration shouldn't be too difficult (see [migration guide](https://docs.pydantic.dev/latest/migration/)), so just trying to get an idea of whether it's worth submitting a PR for this. I would imagine that the reverse issue (people using Pydantic v1 with Anvil) will become an issue as well, though at least there is an obvious path to upgrade, particularly given that v2 allows the use of [v1 features](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features). 

Interested to hear your thoughts!

### PR DESCRIPTION
**Pull request by benogle**
* Closes #56 
* Closes #55 

TODO
* [x] Upgrade everything
* [ ] Fix for multipart uploads
    * `Object of type SerializationIterator is not JSON serializable` Looks like pydantic `model_dump` is converting the file objects to `SerializationIterator` from pydantic core. Not sure how to actually get the value out of the thing
    * https://github.com/pydantic/pydantic/issues/8907

### CODE REVIEW

**Comment by edugmes** [comment]
Hi guys!
Any recent updates regarding this PR? It would be awesome to support the use of Pydantic 2.0.

**Comment by benogle** [comment]
Hey @edugmes, this is currently blocked by https://github.com/pydantic/pydantic/issues/8907. Due to that issue, Pydantic 2.0 breaks multipart uploads

**Comment by cyrusradfar** [comment]
👋🏽  @benogle -- we're grateful for your work with Anvil and are sorry to see that it seems Pydantic isn't able to prioritize the update. Anvil is blocking the upgrade across the core monolith at an Org I'm working with. This is going to be a bigger issue as pydantic 1.1X.xx has more issues with Python 3.13. 

I want to suggest an approach that we can remove once the issue is eventually fixed that will check for the Pydantic version and special case handling in versions after 1.

I can put in a PR, but wanted your perspective of whether you'd be open to this approach to unblock your community from upgrading to Pydantic 2 and beyond.

_Note this isn't final code, just a technical suggestion._

```python
from typing import Any, Union
from io import BufferedReader
import warnings

try:
    from pydantic import BaseModel as PydanticBaseModel
    from pydantic.version import VERSION as PYDANTIC_VERSION
    IS_V2 = not PYDANTIC_VERSION.startswith('1')
except ImportError:
    from pydantic.v1 import BaseModel as PydanticBaseModel
    IS_V2 = False

class FileCompatBaseModel(PydanticBaseModel):
    """
    Base model that maintains Pydantic V1 behavior for file objects when using model_dump()
    """
    def model_dump(self, *args, **kwargs):
        """
        Override model_dump to extract file objects from SerializationIterator in V2
        """
        data = super().model_dump(*args, **kwargs)
        return self._extract_file_objects(data)

    def _extract_file_objects(self, data: Any) -> Any:
        """
        Recursively process dictionary to extract file objects from SerializationIterator
        """
        if isinstance(data, dict):
            return {k: self._extract_file_objects(v) for k, v in data.items()}
        elif isinstance(data, list):
            return [self._extract_file_objects(v) for v in data]
        elif str(type(data)).endswith('SerializationIterator'):
            # Access the underlying file object from SerializationIterator
            try:
                return data.iterator
            except Exception:
                warnings.warn(
                    "Failed to extract file object from SerializationIterator. "
                    "This might cause issues with file handling."
                )
                return data
        return data
```

**Comment by benogle** [comment]
Hey @cyrusradfar, I'm open to anything that works around the issue. If you can make multipart uploads work with pydantic, I'm all ears :)

**Comment by cyrusradfar** [comment]
> Hey @cyrusradfar, I'm open to anything that works around the issue. If you can make multipart uploads work with pydantic, I'm all ears :)

Thank you, I'll work on a solution that's _totally not a hack_...

**Review by newhouse — APPROVED** [review]

**Pull request merged**
